import type {
  KnowledgeChunk,
  KnowledgeDocument,
  Role,
  User,
} from "./types";

export const ROLES: Record<string, Role> = {
  employee: {
    id: "employee",
    label: "普通员工",
    maxPermissionLevel: 1,
    departments: ["全员"],
  },
  manager: {
    id: "manager",
    label: "部门主管",
    maxPermissionLevel: 2,
    departments: ["全员", "本部门", "管理层"],
  },
  admin: {
    id: "admin",
    label: "管理员",
    maxPermissionLevel: 3,
    departments: ["全员", "管理层", "系统管理"],
  },
};

export const MOCK_USERS: User[] = [
  { id: "u1", name: "张明", role: "employee", department: "产品部" },
  { id: "u2", name: "李婷", role: "manager", department: "人力资源部" },
  { id: "u3", name: "王磊", role: "admin", department: "信息技术部" },
];

export const KNOWLEDGE_DOCUMENTS: KnowledgeDocument[] = [
  {
    id: "doc-hr-travel",
    title: "差旅与费用报销管理办法（2025版）",
    category: "hr",
    type: "制度",
    updatedAt: "2025-03-12",
    owner: "人力资源部",
    accessibleDepartments: ["全员"],
    indexStatus: "indexed",
    permissionLevel: 1,
  },
  {
    id: "doc-hr-onboard",
    title: "新员工入职与试用期管理指引",
    category: "hr",
    type: "SOP",
    updatedAt: "2025-02-20",
    owner: "人力资源部",
    accessibleDepartments: ["全员", "用人部门"],
    indexStatus: "indexed",
    permissionLevel: 1,
  },
  {
    id: "doc-it-vpn",
    title: "远程办公 VPN 接入与故障排查手册",
    category: "it",
    type: "操作手册",
    updatedAt: "2025-04-02",
    owner: "信息技术部",
    accessibleDepartments: ["全员"],
    indexStatus: "indexed",
    permissionLevel: 1,
  },
  {
    id: "doc-product-rules",
    title: "智能审批模块 — 业务规则说明 v3.2",
    category: "product",
    type: "产品文档",
    updatedAt: "2025-03-28",
    owner: "产品部",
    accessibleDepartments: ["产品部", "研发部", "客户成功"],
    indexStatus: "indexed",
    permissionLevel: 2,
  },
  {
    id: "doc-finance-budget",
    title: "部门预算编制与审批流程",
    category: "finance",
    type: "制度",
    updatedAt: "2025-01-15",
    owner: "财务部",
    accessibleDepartments: ["管理层", "财务部"],
    indexStatus: "indexed",
    permissionLevel: 2,
  },
  {
    id: "doc-project-alpha",
    title: "Project Alpha 交付里程碑与 RACI",
    category: "project",
    type: "项目资料",
    updatedAt: "2025-04-10",
    owner: "项目管理办公室",
    accessibleDepartments: ["项目组", "管理层"],
    indexStatus: "indexed",
    permissionLevel: 2,
  },
  {
    id: "doc-faq-it",
    title: "IT 服务台常见问题（FAQ）",
    category: "faq",
    type: "FAQ",
    updatedAt: "2025-03-01",
    owner: "信息技术部",
    accessibleDepartments: ["全员"],
    indexStatus: "indexed",
    permissionLevel: 1,
  },
  {
    id: "doc-admin-security",
    title: "知识库权限与审计配置说明（内部）",
    category: "it",
    type: "管理文档",
    updatedAt: "2025-02-08",
    owner: "信息技术部",
    accessibleDepartments: ["系统管理"],
    indexStatus: "indexed",
    permissionLevel: 3,
  },
];

export const KNOWLEDGE_CHUNKS: KnowledgeChunk[] = [
  {
    id: "chunk-travel-1",
    documentId: "doc-hr-travel",
    documentTitle: "差旅与费用报销管理办法（2025版）",
    category: "hr",
    section: "第三章 · 住宿与交通标准",
    content:
      "国内一线城市出差住宿上限为每晚 600 元（含税）；二线城市 450 元；其他城市 350 元。飞机出行原则上选择经济舱，高铁选择二等座。超标部分须直属主管书面审批后方可报销。",
    keywords: ["差旅", "报销", "住宿", "标准", "交通", "经济舱", "审批"],
    department: ["全员"],
    permissionLevel: 1,
    updatedAt: "2025-03-12",
  },
  {
    id: "chunk-travel-2",
    documentId: "doc-hr-travel",
    documentTitle: "差旅与费用报销管理办法（2025版）",
    category: "hr",
    section: "第五章 · 补贴与票据",
    content:
      "出差餐补按自然日计算：一线城市 120 元/天，其他城市 80 元/天。所有报销须在行程结束后 30 日内提交，发票须为增值税电子普通发票或专用发票，并关联 OA 出差申请单号。",
    keywords: ["差旅", "报销", "餐补", "发票", "OA", "30日"],
    department: ["全员"],
    permissionLevel: 1,
    updatedAt: "2025-03-12",
  },
  {
    id: "chunk-onboard-1",
    documentId: "doc-hr-onboard",
    documentTitle: "新员工入职与试用期管理指引",
    category: "hr",
    section: "入职第一周",
    content:
      "入职首日：签署劳动合同、领取工卡、完成信息安全培训、开通企业邮箱与协作账号。第 2-3 天：部门导师介绍岗位职责、阅读部门知识包。第 4-5 天：参加公司级新人培训并完成制度测验（80 分及格）。",
    keywords: ["新员工", "入职", "流程", "培训", "工卡", "邮箱", "试用期"],
    department: ["全员"],
    permissionLevel: 1,
    updatedAt: "2025-02-20",
  },
  {
    id: "chunk-onboard-2",
    documentId: "doc-hr-onboard",
    documentTitle: "新员工入职与试用期管理指引",
    category: "hr",
    section: "试用期考核",
    content:
      "试用期为 3 个月（高管岗位 6 个月）。试用期满前 15 日，导师与 HRBP 共同发起转正评估，包含目标达成、价值观与协作反馈。未通过者可延长试用 1 个月或依法解除。",
    keywords: ["入职", "试用期", "转正", "考核", "HRBP"],
    department: ["全员"],
    permissionLevel: 1,
    updatedAt: "2025-02-20",
  },
  {
    id: "chunk-vpn-1",
    documentId: "doc-it-vpn",
    documentTitle: "远程办公 VPN 接入与故障排查手册",
    category: "it",
    section: "连接前检查",
    content:
      "确认已安装企业指定 VPN 客户端（版本 ≥ 5.2），使用 SSO 账号登录。检查本机系统时间是否自动同步，防火墙需放行 udp/1194。公司网络外首次连接需完成 MFA 二次验证。",
    keywords: ["VPN", "连不上", "连接", "SSO", "MFA", "客户端", "防火墙"],
    department: ["全员"],
    permissionLevel: 1,
    updatedAt: "2025-04-02",
  },
  {
    id: "chunk-vpn-2",
    documentId: "doc-it-vpn",
    documentTitle: "远程办公 VPN 接入与故障排查手册",
    category: "it",
    section: "常见故障处理",
    content:
      "若提示「认证失败」：重置 SSO 密码后等待 15 分钟重试。若提示「隧道建立超时」：切换备用节点 cn-east-2，或关闭本地代理软件。仍无法连接时，在 IT 服务台提交工单，附上客户端日志（帮助 → 导出诊断）。",
    keywords: ["VPN", "连不上", "故障", "认证失败", "超时", "工单", "日志"],
    department: ["全员"],
    permissionLevel: 1,
    updatedAt: "2025-04-02",
  },
  {
    id: "chunk-product-1",
    documentId: "doc-product-rules",
    documentTitle: "智能审批模块 — 业务规则说明 v3.2",
    category: "product",
    section: "2.1 自动通过条件",
    content:
      "当申请类型为「差旅报销」且金额 ≤ 3000 元、发票验真通过、关联出差单状态为已批准时，系统自动通过，无需人工审批。超过 3000 元或存在异常发票标记时，流转至直属主管。",
    keywords: ["产品", "功能", "业务规则", "审批", "自动通过", "报销", "3000"],
    department: ["产品部", "研发部"],
    permissionLevel: 2,
    updatedAt: "2025-03-28",
  },
  {
    id: "chunk-product-2",
    documentId: "doc-product-rules",
    documentTitle: "智能审批模块 — 业务规则说明 v3.2",
    category: "product",
    section: "2.3 风控拦截",
    content:
      "同一员工 7 日内累计提交 ≥ 5 笔同类报销时，触发风控复核；节假日期间提交的紧急采购须附加业务说明附件，否则驳回。所有规则变更须在产品 changelog 登记并通知客户成功团队。",
    keywords: ["产品", "业务规则", "风控", "报销", "驳回", "changelog"],
    department: ["产品部", "研发部"],
    permissionLevel: 2,
    updatedAt: "2025-03-28",
  },
  {
    id: "chunk-finance-1",
    documentId: "doc-finance-budget",
    documentTitle: "部门预算编制与审批流程",
    category: "finance",
    section: "审批链",
    content:
      "年度预算由部门主管起草，财务部复核后提交管理层审批。季度滚动调整幅度超过原预算 10% 的，须追加 CFO 签字。普通员工不可查看其他部门预算明细。",
    keywords: ["预算", "审批", "财务", "CFO", "部门"],
    department: ["管理层", "财务部"],
    permissionLevel: 2,
    updatedAt: "2025-01-15",
  },
  {
    id: "chunk-admin-1",
    documentId: "doc-admin-security",
    documentTitle: "知识库权限与审计配置说明（内部）",
    category: "it",
    section: "权限模型",
    content:
      "知识库采用三级权限：L1 全员可读、L2 主管及以上、L3 仅管理员。向量索引每日 02:00 增量更新，权限变更后 15 分钟内失效旧 token 的检索结果。所有问答日志保留 180 天供审计。",
    keywords: ["权限", "审计", "知识库", "管理员", "索引", "向量"],
    department: ["系统管理"],
    permissionLevel: 3,
    updatedAt: "2025-02-08",
  },
];
