import type { ParadigmPrdConfig } from "./types";
import {
  TEN_STEP_FLOW,
  defaultAcceptance,
  defaultDataSchema,
  defaultMvp,
  defaultSecurity,
  defaultTechStack,
  promptPack,
} from "./shared";

function mod(
  base: Partial<ParadigmPrdConfig> &
    Pick<ParadigmPrdConfig, "slug" | "productName" | "oneLiner" | "businessBackground">,
): ParadigmPrdConfig {
  const { productName: name } = base;
  const defaults: ParadigmPrdConfig = {
    slug: base.slug,
    productName: name,
    oneLiner: base.oneLiner,
    businessBackground: base.businessBackground,
    painPoints: [],
    whyAgent: [],
    traditionalLimits: [],
    agentValue: [],
    targetUsers: [],
    scenarios: [],
    boundaries: [],
    notSolving: [],
    userNeedsTable: [],
    agentGoal: "",
    agentInputs: [],
    agentOutputs: [],
    agentContext: [],
    agentTools: [],
    agentData: [],
    agentReasoning: [],
    agentWorkflow: [],
    agentExceptions: [],
    humanConfirmNodes: [],
    featureModules: [],
    tenStepFlow: TEN_STEP_FLOW,
    mainFlow: [],
    branchFlows: [],
    exceptionFlows: [],
    humanFlows: [],
    pages: [],
    dataSchema: defaultDataSchema(name),
    prompts: promptPack(`企业${name} Agent`, "知识"),
    security: defaultSecurity(name),
    mvpTable: defaultMvp(["核心 Demo"], ["全自动无人工"]),
    acceptance: defaultAcceptance(),
    techStack: defaultTechStack(),
    finalNote: `${name} PRD 可直接用于立项评审与研发拆分。`,
  };
  return { ...defaults, ...base };
}

export const PRD_CONFIGS: ParadigmPrdConfig[] = [
  mod({
    slug: "paradigm-01",
    productName: "企业知识库 AI 问答 Agent",
    oneLiner: "可溯源、可权限管控的企业制度与知识问答智能体",
    businessBackground:
      "大型企业内部制度、SOP、产品文档分散在 OA、网盘与 Wiki，员工检索成本高，HR/IT 重复答疑占用大量人力。",
    painPoints: [
      "找不到最新版制度，误用过期文档",
      "搜索关键词不匹配自然语言问题",
      "敏感制度不知是否有权查看",
      "答案无法追溯来源，合规审计困难",
    ],
    whyAgent: [
      "自然语言理解 + RAG 可精准定位段落",
      "可按角色过滤文档后再生成",
      "结构化输出结论、步骤与引用",
    ],
    traditionalLimits: [
      "关键词搜索返回整篇 PDF",
      "FAQ 静态无法覆盖长尾问题",
      "人工答疑不可规模化",
    ],
    agentValue: ["7×24 秒级响应", "答案可审计", "降低 30%+ 重复咨询工单"],
    targetUsers: ["全体员工", "HR/行政", "IT 服务台", "知识库管理员"],
    scenarios: ["差旅报销标准", "入职流程", "产品规格", "安全合规查询"],
    boundaries: ["制度与 FAQ 问答", "引用溯源", "三角色权限模拟"],
    notSolving: ["代替法务最终解释", "自动修改制度正文", "跨租户数据混合"],
    userNeedsTable: [
      ["用户角色", "员工：快速查规则；管理员：维护知识库；主管：看使用情况"],
      ["用户目标", "30 秒内获得可信答案与办事步骤"],
      ["用户任务", "提问→阅读引用→按步骤执行→反馈"],
      ["用户痛点", "搜不到、不敢信、不知道找谁"],
      ["高频场景", "报销、休假、IT 报障指引"],
      ["低频高价值", "合规条款、并购期特殊政策"],
      ["成功标准", "引用正确、步骤可执行、无越权文档"],
    ],
    agentGoal: "在权限范围内检索企业知识并生成可溯源的结构化答复",
    agentInputs: ["自然语言问题", "用户角色", "部门上下文"],
    agentOutputs: ["结论", "步骤列表", "引用片段", "置信度", "相关文档链接"],
    agentContext: ["会话历史", "用户权限集", "检索 Top-K Chunks"],
    agentTools: ["searchKnowledgeChunks", "getDocumentMeta", "checkPermission"],
    agentData: ["向量索引", "文档元数据", "权限 ACL 表"],
    agentReasoning: ["问题改写→检索→重排→仅基于 Chunk 生成→校验引用"],
    agentWorkflow: ["鉴权", "检索", "生成", "展示引用", "收集反馈"],
    agentExceptions: ["无命中：提示换关键词或转人工", "低置信：标注需核实"],
    humanConfirmNodes: ["首次查看机密文档", "用户点击「转人工」"],
    featureModules: [
      ["工作台", "统一提问入口", "输入问题", "意图+检索", "query,role", "RAG API", "已登录", "结构化答案", "无权限", "P0"],
      ["回答面板", "展示结论步骤", "展开引用", "生成+引用绑定", "citations", "LLM", "检索成功", "Answer JSON", "幻觉", "P0"],
      ["知识库", "文档列表", "筛选分类", "元数据查询", "doc_id", "CMS API", "读权限", "文档卡片", "同步延迟", "P1"],
      ["权限模拟", "角色切换", "切换角色", "checkPermission", "role", "AuthZ", "管理员配置", "过滤结果", "配置错误", "P0"],
    ],
    mainFlow: ["登录→提问→检索→生成→引用确认→反馈"],
    branchFlows: ["机密文档→权限拒绝提示", "低置信→建议联系主管部门"],
    exceptionFlows: ["向量库超时→缓存 FAQ 降级"],
    humanFlows: ["转人工→创建工单草稿（需确认）"],
    pages: [
      ["工作台", "快速提问", "输入框+推荐问题", "输入/发送", "检索中/生成中", "Enter 发送"],
      ["回答详情", "阅读与溯源", "结论/步骤/引用抽屉", "点开引用", "置信度标签", "侧栏原文"],
      ["知识库", "浏览文档", "列表+搜索", "筛选", "—", "权限锁图标"],
      ["管理", "权限与审计", "角色/日志表", "导出", "—", "仅管理员"],
    ],
    prompts: promptPack("企业知识库问答专家", "制度与SOP"),
    mvpTable: defaultMvp(
      ["问答+引用+三角色权限+反馈"],
      ["多模态文档", "自动知识抽取", "工作流写回"],
    ),
    finalNote: "企业知识库 Agent PRD：强调 RAG 可溯源与权限，而非开放式聊天。",
  }),

  mod({
    slug: "paradigm-02",
    productName: "ToB 智能客服 Agent",
    oneLiner: "AI 自动应答 + 坐席协同 + 质检闭环的 ToB 服务智能体",
    businessBackground: "ToB 客户服务涉及产品、合同、实施与故障，问题长尾且专业，纯人工成本高，纯机器人满意度低。",
    painPoints: ["响应慢", "重复 FAQ", "复杂问题机器人听不懂", "质检抽样覆盖率低"],
    whyAgent: ["意图识别+知识检索", "多轮澄清", "适时转人工并带上下文"],
    traditionalLimits: ["规则树维护成本高", "坐席系统与知识库割裂"],
    agentValue: ["提升 FCR", "降低平均处理时长", "质检自动化"],
    targetUsers: ["客户", "客服坐席", "客服主管"],
    scenarios: ["产品咨询", "报障", "账单", "升级投诉"],
    boundaries: ["文本客服", "工单创建", "质检报告"],
    notSolving: ["现场硬件维修", "法律诉讼代理"],
    userNeedsTable: [
      ["角色", "客户要快速解决；坐席要辅助；主管要质量"],
      ["目标", "问题闭环、可追溯"],
      ["任务", "对话→识别→答复/转人工→工单"],
      ["痛点", "转人工后重复描述"],
      ["高频", "账号、版本、常见故障"],
      ["低频高价值", "大客户升级、合同争议"],
      ["成功", "一次解决或顺畅转人工"],
    ],
    agentGoal: "理解客户意图，基于 FAQ 答复或升级至人工并创建工单",
    agentInputs: ["客户消息", "客户等级", "产品版本"],
    agentOutputs: ["回复文本", "意图标签", "工单草稿", "是否转人工"],
    agentContext: ["会话历史", "客户 360", "FAQ 索引"],
    agentTools: ["detectIntent", "searchFAQ", "createTicket", "transferHuman"],
    agentData: ["FAQ", "产品目录", "工单系统"],
    agentReasoning: ["意图→检索→置信度→转人工规则"],
    agentWorkflow: ["接待", "识别", "答复", "转人工判断", "工单", "质检"],
    agentExceptions: ["辱骂→安抚+升级", "API 失败→模板致歉"],
    humanConfirmNodes: ["创建工单前客户确认联系方式", "赔付承诺需坐席确认"],
    featureModules: [
      ["客户聊天", "C 端对话", "发消息", "reply/transfer", "message", "LLM+FAQ", "—", "气泡回复", "超时", "P0"],
      ["坐席台", "辅助坐席", "采纳建议", "summarize+建议", "session_id", "CRM", "坐席登录", "话术卡", "—", "P0"],
      ["质检", "会话评分", "抽检", "qualityReport", "transcript", "LLM", "会话结束", "报告", "—", "P1"],
    ],
    mainFlow: ["消息→意图→FAQ→回复或转人工"],
    branchFlows: ["VIP 客户→优先队列", "多轮澄清→槽位填充"],
    exceptionFlows: ["FAQ 无命中→转人工"],
    humanFlows: ["坐席接管→AI 建议继续生成"],
    pages: [
      ["客户视图", "咨询", "聊天窗", "输入", "输入中", "转人工按钮"],
      ["坐席视图", "处理", "会话+建议", "接管", "AI 辅助", "一键工单"],
      ["主管视图", "质检", "列表+分数", "复盘", "—", "趋势图"],
    ],
    prompts: promptPack("ToB 客服专家", "FAQ与服务政策"),
    finalNote: "智能客服 Agent：核心是意图、转人工与工单，不是无限闲聊。",
  }),

  mod({
    slug: "paradigm-03",
    productName: "销售 Copilot Agent",
    oneLiner: "贯穿客户洞察、拜访、方案、纪要跟进的售前智能体",
    businessBackground: "ToB 销售大量时间花在资料整理、方案撰写与内部协调，CRM 数据利用率低。",
    painPoints: ["拜访前不知客户痛点", "方案同质化", "会后跟进滞后"],
    whyAgent: ["整合 CRM", "生成个性化内容", "结构化纪要"],
    traditionalLimits: ["CRM 只存数据不产出洞察", "模板方案缺乏针对性"],
    agentValue: ["缩短方案周期", "提高赢单率", "销售行为标准化"],
    targetUsers: ["销售", "售前", "销售经理"],
    scenarios: ["拜访准备", "方案", "纪要", "跟进邮件"],
    boundaries: ["销售赋能", "不自动报价审批"],
    notSolving: ["合同法务终审", "代客户签约"],
    userNeedsTable: [
      ["角色", "销售要赢单；经理要预测"],
      ["目标", "每次客户互动有准备、有沉淀"],
      ["任务", "选客户→生成材料→会后跟进"],
      ["痛点", "信息散、写材料慢"],
      ["高频", "拜访 brief、跟进邮件"],
      ["低频高价值", "招投标方案"],
      ["成功", "客户感知专业、内部流程留痕"],
    ],
    agentGoal: "基于客户数据生成可执行的销售材料与下一步行动",
    agentInputs: ["客户 ID", "会议录音/笔记", "产品目录"],
    agentOutputs: ["洞察", "方案", "纪要", "邮件草稿", "next action"],
    agentContext: ["CRM 商机阶段", "历史互动", "竞品信息"],
    agentTools: ["analyzeCustomer", "generateProposal", "summarizeMeeting"],
    agentData: ["CRM", "产品库", "案例库"],
    agentReasoning: ["阶段判断→选模板→个性化填充→合规检查"],
    agentWorkflow: ["选客户", "分析", "生成", "编辑", "同步 CRM"],
    agentExceptions: ["数据缺失→追问销售补充"],
    humanConfirmNodes: ["对外发送邮件", "方案中价格与折扣"],
    featureModules: [
      ["客户360", "洞察", "查看客户", "analyzeCustomer", "account_id", "CRM API", "权限", "洞察卡", "无数据", "P0"],
      ["方案", "生成方案", "填需求", "generateProposal", "requirements", "LLM", "客户已选", "方案 doc", "—", "P0"],
      ["纪要", "会后", "粘贴/上传", "summarizeMeeting", "transcript", "LLM", "—", "纪要+待办", "—", "P0"],
    ],
    mainFlow: ["客户→洞察→材料→编辑→CRM 同步"],
    branchFlows: ["竞标→长方案分支"],
    exceptionFlows: ["CRM 不可用→本地草稿"],
    humanFlows: ["经理审批折扣条款"],
    pages: [
      ["工作台", "导航", "侧栏", "切换模块", "—", "—"],
      ["客户360", "洞察", "画像卡", "刷新", "分析中", "风险标签"],
      ["方案编辑", "产出", "富文本", "编辑/导出", "生成中", "版本对比"],
    ],
    prompts: promptPack("ToB 销售顾问", "CRM与方案库"),
    finalNote: "销售 Agent 输出必须可编辑且可回写 CRM。",
  }),

  mod({
    slug: "paradigm-04",
    productName: "运营增长 Copilot Agent",
    oneLiner: "指标洞察、异常归因与自然语言增长分析智能体",
    businessBackground: "运营人员需每日盯盘、找异常、写策略，数据分散在 BI 与广告平台。",
    painPoints: ["指标多不知先看啥", "归因靠经验", "复盘撰写耗时"],
    whyAgent: ["自动异常检测", "NL 解读指标", "生成活动/复盘"],
    traditionalLimits: ["BI 只展示不解释", "Excel 复盘重复劳动"],
    agentValue: ["缩短决策周期", "统一分析口径"],
    targetUsers: ["增长运营", "市场", "运营负责人"],
    scenarios: ["日报", "异常", "活动策划", "大促复盘"],
    boundaries: ["分析与建议", "不自动投放"],
    notSolving: ["财务结账", "实时竞价算法"],
    userNeedsTable: [
      ["角色", "运营要增长；负责人要方向"],
      ["目标", "数据到动作"],
      ["任务", "看板→提问→策略"],
      ["痛点", "归因慢"],
      ["高频", "GMV/转化波动"],
      ["低频高价值", "全链路战役策划"],
      ["成功", "策略可执行、可衡量"],
    ],
    agentGoal: "发现指标异常并输出可执行增长建议",
    agentInputs: ["指标 API 数据", "NL 问题", "活动参数"],
    agentOutputs: ["诊断", "归因", "活动方案", "复盘报告"],
    agentContext: ["指标字典", "历史活动", "渠道结构"],
    agentTools: ["detectAnomalies", "analyzeMetric", "generateCampaignPlan"],
    agentData: ["数仓指标", "广告花费", "活动配置"],
    agentReasoning: ["阈值+趋势→归因假设→验证→建议"],
    agentWorkflow: ["拉数", "检测", "分析", "输出", "复盘"],
    agentExceptions: ["数据延迟→标注时效"],
    humanConfirmNodes: ["预算调整建议", "对外发布活动"],
    featureModules: [
      ["看板", "指标", "查看", "拉取指标", "metric_id", "BI API", "—", "图表", "延迟", "P0"],
      ["分析", "NL", "提问", "analyzeMetric", "query", "LLM", "—", "解读", "—", "P0"],
      ["活动", "方案", "填目标", "generateCampaignPlan", "budget", "LLM", "—", "方案", "—", "P1"],
    ],
    mainFlow: ["看板→异常→NL 分析→策略"],
    branchFlows: ["活动前/后不同模板"],
    exceptionFlows: ["指标口径变更→提示"],
    humanFlows: ["大额预算→负责人确认"],
    pages: [
      ["Dashboard", "总览", "图表", "筛选", "—", "异常高亮"],
      ["分析", "问答", "输入+图表", "提问", "分析中", "引用指标"],
      ["复盘", "报告", "编辑器", "导出", "—", "模板"],
    ],
    prompts: promptPack("增长分析专家", "运营指标"),
    finalNote: "运营 Agent 须绑定指标语义层保证口径一致。",
  }),

  mod({
    slug: "paradigm-05",
    productName: "数据分析 BI Copilot Agent",
    oneLiner: "指标语义层 + NL2SQL + 智能解读的 BI 智能体",
    businessBackground: "业务人员取数依赖数据团队，SQL 门槛高，指标口径常不一致。",
    painPoints: ["排队取数", "SQL 难写", "口径争议"],
    whyAgent: ["语义层映射", "生成可审查 SQL", "结果解读"],
    traditionalLimits: ["自助 BI 仍要懂维度", "SQL 易错"],
    agentValue: ["自助分析", "释放数据团队"],
    targetUsers: ["分析师", "运营", "PM", "管理层"],
    scenarios: ["临时查数", "漏斗", "周会解读"],
    boundaries: ["只读查询", "不直接改数仓"],
    notSolving: ["ETL 开发", "实时流计算"],
    userNeedsTable: [
      ["角色", "业务要自助；分析师要效率"],
      ["目标", "可信取数+读懂"],
      ["任务", "提问→SQL→图表→解读"],
      ["痛点", "怕查错"],
      ["高频", "漏斗、趋势"],
      ["低频高价值", "跨域 join 分析"],
      ["成功", "SQL 可复现、解读准确"],
    ],
    agentGoal: "将自然语言转为可执行查询并给出业务解读",
    agentInputs: ["NL 问题", "指标/维度选择"],
    agentOutputs: ["SQL", "结果表", "图表 spec", "解读文本"],
    agentContext: ["指标目录", "表血缘", "权限行级过滤"],
    agentTools: ["generateSQL", "executeQuery", "explainResult"],
    agentData: ["数仓", "语义层", "查询日志"],
    agentReasoning: ["映射指标→生成 SQL→审计→执行→解读"],
    agentWorkflow: ["理解", "生成 SQL", "用户确认", "执行", "可视化"],
    agentExceptions: ["SQL 失败→修正重试", "超时→采样"],
    humanConfirmNodes: ["执行 SQL 前", "导出大批量数据"],
    featureModules: [
      ["目录", "指标", "浏览", "lookup", "metric", "元数据", "—", "定义", "—", "P0"],
      ["SQL Lab", "取数", "NL/SQL", "generateSQL", "sql", "Trino", "只读账号", "结果集", "超时", "P0"],
      ["漏斗", "分析", "配置", "compute", "steps", "BI", "—", "漏斗图", "—", "P1"],
    ],
    mainFlow: ["提问→SQL 草稿→确认→执行→解读"],
    branchFlows: ["探索性分析→多轮 refine"],
    exceptionFlows: ["权限不足→脱敏提示"],
    humanFlows: ["敏感字段→额外审批"],
    pages: [
      ["Dashboard", "KPI", "卡片", "下钻", "—", "—"],
      ["SQL Lab", "取数", "编辑器", "运行", "执行计划", "语法高亮"],
      ["目录", "口径", "树形", "搜索", "—", "定义悬浮"],
    ],
    prompts: promptPack("BI 分析助手", "指标语义层"),
    finalNote: "BI Agent 核心是 SQL 可审查与语义层，不是黑盒报数。",
  }),

  mod({
    slug: "paradigm-06",
    productName: "企业流程自动化 Agent",
    oneLiner: "自然语言驱动 OA/ERP 工具调用与人工确认的执行型智能体",
    businessBackground: "入职、采购、审批等流程跨多个系统，人工点击路径长，RPA 脚本脆弱。",
    painPoints: ["重复录入", "系统割裂", "合规怕自动乱动"],
    whyAgent: ["理解目标拆步骤", "调用 API", "关键点人工确认"],
    traditionalLimits: ["RPA 怕 UI 变化", "纯工作流不理解 NL"],
    agentValue: ["端到端自动化", "可审计", "可暂停确认"],
    targetUsers: ["业务人员", "IT", "主管"],
    scenarios: ["入职开通", "采购", "出差", "导出"],
    boundaries: ["已注册工具", "可配置确认点"],
    notSolving: ["无 API 的老系统屏幕操作（MVP）"],
    userNeedsTable: [
      ["角色", "业务要省事；IT 要可控"],
      ["目标", "一句话办完"],
      ["任务", "描述目标→确认步骤→执行"],
      ["痛点", "怕 AI 乱操作"],
      ["高频", "账号、申请单"],
      ["低频高价值", "跨系统编排"],
      ["成功", "步骤透明、可回滚"],
    ],
    agentGoal: "将自然语言目标转为可执行计划并安全调用企业工具",
    agentInputs: ["目标描述", "表单参数", "用户身份"],
    agentOutputs: ["计划", "每步结果", "审计日志"],
    agentContext: ["工具清单", "权限", "历史执行"],
    agentTools: ["parseTaskGoal", "planSteps", "callMockTool", "confirmStep"],
    agentData: ["OA", "HR", "IAM"],
    agentReasoning: ["解析→规划→风险评估→逐步执行"],
    agentWorkflow: ["输入", "规划", "展示", "确认", "执行", "审计"],
    agentExceptions: ["工具失败→重试/跳过/中止"],
    humanConfirmNodes: ["权限变更", "资金相关", "对外通知"],
    featureModules: [
      ["工作台", "下达目标", "输入", "parse+plan", "goal", "LLM", "登录", "计划", "—", "P0"],
      ["时间线", "执行", "确认", "executeStep", "step_id", "Tools", "计划批准", "状态", "失败", "P0"],
      ["审计", "留痕", "查看", "log", "—", "DB", "—", "日志", "—", "P0"],
    ],
    mainFlow: ["目标→计划→逐步确认执行"],
    branchFlows: ["并行步骤", "条件分支"],
    exceptionFlows: ["失败回滚提示"],
    humanFlows: ["高风险卡暂停"],
    pages: [
      ["工作台", "输入", "NL 框", "提交", "规划中", "步骤预览"],
      ["时间线", "进度", "步骤条", "确认", "执行中", "失败重试"],
      ["审计", "合规", "表格", "筛选", "—", "导出"],
    ],
    prompts: promptPack("流程执行 Agent", "企业工具与政策"),
    finalNote: "流程 Agent 必须「计划可见 + 确认可配 + 全审计」。",
  }),

  mod({
    slug: "paradigm-07",
    productName: "企业 AI 文档生成 Agent",
    oneLiner: "从结构化输入到大纲、分节正文与引用的文档生产智能体",
    businessBackground: "标书、方案、合同等文档重复度高，多人协作版本混乱。",
    painPoints: ["写大纲耗时", "风格不一", "引用难管理"],
    whyAgent: ["模板+生成", "分节迭代", "来源绑定"],
    traditionalLimits: ["Word 模板不智能", "纯 LLM 易幻觉"],
    agentValue: ["提速 50%+", "合规引用", "审批留痕"],
    targetUsers: ["售前", "PM", "法务", "市场"],
    scenarios: ["标书", "方案", "合同初稿", "汇报"],
    boundaries: ["生成与协作", "不替代签章"],
    notSolving: ["法院文书送达"],
    userNeedsTable: [
      ["角色", "写作者要速度；法务要可控"],
      ["目标", "高质量初稿"],
      ["任务", "选类型→填表→生成→审"],
      ["痛点", "章节遗漏"],
      ["高频", "技术方案", "会议纪要"],
      ["低频高价值", "整本标书"],
      ["成功", "可审批、可导出"],
    ],
    agentGoal: "按企业模板生成带引用的多章节文档",
    agentInputs: ["文档类型", "表单字段", "参考素材"],
    agentOutputs: ["大纲", "章节 HTML/MD", "引用列表"],
    agentContext: ["模板库", "企业案例", "术语表"],
    agentTools: ["generateOutline", "generateSection", "polishSection"],
    agentData: ["模板", "素材库", "版本库"],
    agentReasoning: ["类型→大纲→逐节 RAG→润色"],
    agentWorkflow: ["选型", "表单", "大纲确认", "分节生成", "审批"],
    agentExceptions: ["素材不足→提示上传"],
    humanConfirmNodes: ["对外发送", "法务条款变更"],
    featureModules: [
      ["类型", "选型", "点击", "loadTemplate", "type", "—", "—", "表单", "—", "P0"],
      ["大纲", "结构", "调整", "generateOutline", "fields", "LLM", "表单完成", "大纲", "—", "P0"],
      ["编辑器", "正文", "编辑", "generateSection", "section_id", "LLM+RAG", "大纲锁定", "章节", "幻觉", "P0"],
    ],
    mainFlow: ["类型→表单→大纲→分节→审批→导出"],
    branchFlows: ["标书/合同不同模板"],
    exceptionFlows: ["生成失败→重试单节"],
    humanFlows: ["法务审批节点"],
    pages: [
      ["选型", "开始", "卡片", "选择", "—", "—"],
      ["大纲", "结构", "树", "拖拽", "生成中", "锁定"],
      ["编辑", "写作", "分节", "润色", "生成中", "引用抽屉"],
    ],
    prompts: promptPack("企业文档写作 Agent", "模板与案例库"),
    finalNote: "文档 Agent 分节生成+引用是降低幻觉关键。",
  }),

  mod({
    slug: "paradigm-08",
    productName: "会议 Copilot Agent",
    oneLiner: "转写、纪要、待办与决策提取的会议智能体",
    businessBackground: "会议多但沉淀少，会后整理占时，Action Item 易丢失。",
    painPoints: ["纪要慢", "待办不清", "决策无记录"],
    whyAgent: ["长文本结构化", "说话人分离", "同步项目工具"],
    traditionalLimits: ["录音堆积无人听", "模板纪要空洞"],
    agentValue: ["会后 5 分钟出纪要", "执行率提升"],
    targetUsers: ["PM", "销售", "管理者"],
    scenarios: ["周会", "客户会", "评审"],
    boundaries: ["会议内容易", "同步为模拟"],
    notSolving: ["替代参会决策"],
    userNeedsTable: [
      ["角色", "组织者要沉淀；参与者要清晰待办"],
      ["目标", "可执行的会后资产"],
      ["任务", "录音→纪要→同步"],
      ["痛点", "谁做什么不清楚"],
      ["高频", "内部站会"],
      ["低频高价值", "客户纪要入 CRM"],
      ["成功", "待办有主责有时限"],
    ],
    agentGoal: "将会议内容转为纪要、待办与决策记录",
    agentInputs: ["音频/转写文本", "参会人", "会议类型"],
    agentOutputs: ["纪要", "Action Items", "Decisions", "质量分"],
    agentContext: ["议程", "历史会议", "项目上下文"],
    agentTools: ["transcribe", "summarize", "extractActions", "syncCRM"],
    agentData: ["录音", "日历", "项目"],
    agentReasoning: ["转写→分段→抽取→归类→质检"],
    agentWorkflow: ["上传", "转写", "生成", "确认", "同步"],
    agentExceptions: ["音质差→提示人工校对"],
    humanConfirmNodes: ["同步到 CRM/项目", "对外发送纪要"],
    featureModules: [
      ["列表", "会议", "选择", "load", "meeting_id", "日历", "—", "卡片", "—", "P0"],
      ["转写", "原文", "播放", "transcribe", "audio", "ASR", "文件", "文本", "噪音", "P0"],
      ["纪要", "产出", "编辑", "summarize", "transcript", "LLM", "转写完成", "纪要", "—", "P0"],
    ],
    mainFlow: ["会议→转写→纪要→待办→同步"],
    branchFlows: ["客户会→CRM 字段映射"],
    exceptionFlows: ["转写超时→分段"],
    humanFlows: ["确认后同步"],
    pages: [
      ["列表", "入口", "列表", "进入", "—", "—"],
      ["详情", "处理", "Tab", "编辑", "生成中", "说话人色"],
      ["质量", "评估", "雷达", "查看", "—", "建议"],
    ],
    prompts: promptPack("会议秘书 Agent", "会议转写与项目"),
    finalNote: "会议 Agent 重点是结构化抽取而非摘要散文。",
  }),

  mod({
    slug: "paradigm-09",
    productName: "研发 Copilot Agent",
    oneLiner: "需求拆解、代码解释、测试、日志与 CR 的研发效能智能体",
    businessBackground: "研发知识碎片化，排障与 CR 依赖资深工程师，需求到任务转换慢。",
    painPoints: ["老代码难懂", "测试遗漏", "日志排查累"],
    whyAgent: ["代码理解", "结构化输出", "接 CI/仓库"],
    traditionalLimits: ["静态分析不懂业务", "Chat 不结构化"],
    agentValue: ["降本增效", "知识沉淀"],
    targetUsers: ["前后端", "测试", "运维", "TL"],
    scenarios: ["PRD 拆解", "CR", "排障", "API 文档"],
    boundaries: ["建议不自动合码"],
    notSolving: ["替代安全渗透测试"],
    userNeedsTable: [
      ["角色", "开发要速度；TL 要质量"],
      ["目标", "可执行研发产出"],
      ["任务", "贴代码/日志→分析"],
      ["痛点", "上下文切换"],
      ["高频", "日志、小 CR"],
      ["低频高价值", "大需求拆解"],
      ["成功", "建议可落地"],
    ],
    agentGoal: "理解研发工件并输出可执行任务与建议",
    agentInputs: ["PRD/代码/日志/diff"],
    agentOutputs: ["任务列表", "解释", "用例", "CR 意见"],
    agentContext: ["仓库", "规范", "历史 incident"],
    agentTools: ["analyzeRequirement", "explainCode", "reviewCode"],
    agentData: ["Git", "CI 日志", "接口 spec"],
    agentReasoning: ["路由模块→静态+LLM→结构化"],
    agentWorkflow: ["输入", "路由", "分析", "展示", "反馈"],
    agentExceptions: ["代码过长→分段"],
    humanConfirmNodes: ["自动建分支/改配置"],
    featureModules: [
      ["工作台", "路由", "输入", "routeNL", "text", "LLM", "—", "模块", "—", "P0"],
      ["需求", "拆解", "PRD", "analyzeRequirement", "prd", "LLM", "—", "任务", "—", "P0"],
      ["CR", "审查", "diff", "reviewCode", "patch", "LLM", "—", "findings", "—", "P0"],
    ],
    mainFlow: ["选模块→输入→分析→结果"],
    branchFlows: ["NL 自动路由"],
    exceptionFlows: ["无法访问仓库→仅文本分析"],
    humanFlows: ["合并代码需人审"],
    pages: [
      ["首页", "入口", "卡片", "选择", "—", "—"],
      ["分屏", "作业", "输入+结果", "分析", "运行中", "代码高亮"],
    ],
    prompts: promptPack("资深研发工程师 Agent", "代码与规范"),
    finalNote: "研发 Agent 输出必须结构化，便于接工单与 CI。",
  }),

  mod({
    slug: "paradigm-10",
    productName: "质检风控 Copilot Agent",
    oneLiner: "质检标准、缺陷、抽检与异常审核的智能体",
    businessBackground: "制造与电商风控依赖专家经验，标准复杂，异常判断主观性强。",
    painPoints: ["标准难读", "缺陷归因慢", "风控规则难配"],
    whyAgent: ["标准解读", "模式匹配", "规则建议"],
    traditionalLimits: ["SPC 只报警不解释", "规则引擎维护难"],
    agentValue: ["一致性", "可追溯", "降误杀"],
    targetUsers: ["QC", "风控", "合规"],
    scenarios: ["缺陷", "AQL", "订单审核"],
    boundaries: ["建议不自动放行"],
    notSolving: ["替代实验室检测"],
    userNeedsTable: [
      ["角色", "QC 要判定；风控要拦截"],
      ["目标", "有据可依"],
      ["任务", "输入→风险→建议"],
      ["痛点", "标准版本多"],
      ["高频", "缺陷记录"],
      ["低频高价值", "批量遏制"],
      ["成功", "等级正确、可升级"],
    ],
    agentGoal: "识别质量与业务风险并给出依据与处置建议",
    agentInputs: ["标准文本", "缺陷描述", "订单特征"],
    agentOutputs: ["风险项", "等级", "依据", "处置"],
    agentContext: ["MES", "历史案例", "规则库"],
    agentTools: ["interpretStandard", "analyzeDefect", "reviewAnomaly"],
    agentData: ["MES", "订单", "标准库"],
    agentReasoning: ["关键词+规则+案例检索"],
    agentWorkflow: ["输入", "识别", "分级", "建议", "升级"],
    agentExceptions: ["数据不全→要求补录"],
    humanConfirmNodes: ["批量停线", "订单放行/拦截"],
    featureModules: [
      ["标准", "解读", "粘贴", "interpretStandard", "text", "LLM", "—", "要点", "—", "P0"],
      ["缺陷", "分析", "录入", "analyzeDefect", "batch", "LLM+MES", "—", "根因", "—", "P0"],
      ["异常", "审核", "订单", "reviewAnomaly", "order", "风控", "—", "拦截建议", "—", "P0"],
    ],
    mainFlow: ["录入→分析→分级→处置"],
    branchFlows: ["合规月报分支"],
    exceptionFlows: ["超阈值→升级"],
    humanFlows: ["主管复核"],
    pages: [
      ["工作台", "模块", "卡片", "选择", "—", "—"],
      ["分析", "结果", "结构化", "确认", "—", "等级徽章"],
    ],
    prompts: promptPack("质检风控专家 Agent", "标准与案例"),
    finalNote: "质检风控 Agent 高风险动作必须人工确认。",
  }),

  mod({
    slug: "paradigm-11",
    productName: "企业 AI 培训 Agent",
    oneLiner: "学习路径、陪练、测验与成长报告的智能体",
    businessBackground: "企业培训一刀切，学完缺练习，效果难衡量。",
    painPoints: ["不知学什么", "缺场景练习", "主管看不见效果"],
    whyAgent: ["个性化路径", "角色扮演", "自动出题"],
    traditionalLimits: ["LMS 只播课", "线下陪练贵"],
    agentValue: ["规模化陪练", "可衡量"],
    targetUsers: ["员工", "销售/客服", "HR", "主管"],
    scenarios: ["入职", "话术陪练", "考试"],
    boundaries: ["培训不代替执业资格认证"],
    notSolving: ["替代线下实操设备培训"],
    userNeedsTable: [
      ["角色", "学员要成长；HR 要效率"],
      ["目标", "能力可测"],
      ["任务", "学练测评"],
      ["痛点", "枯燥、无反馈"],
      ["高频", "问答、陪练"],
      ["低频高价值", "管理沟通陪练"],
      ["成功", "分数提升、路径完成"],
    ],
    agentGoal: "按岗位推送学习并评估陪练与测验表现",
    agentInputs: ["岗位", "问题", "陪练对话", "答卷"],
    agentOutputs: ["路径", "回答", "评分", "报告"],
    agentContext: ["课程库", "画像", "历史成绩"],
    agentTools: ["generatePath", "simulateRoleplay", "gradeQuiz"],
    agentData: ["LMS", "HRIS"],
    agentReasoning: ["画像→推荐→练评闭环"],
    agentWorkflow: ["画像", "路径", "学练测", "报告"],
    agentExceptions: ["作弊检测→提示"],
    humanConfirmNodes: ["认证结论", "晋升建议"],
    featureModules: [
      ["路径", "规划", "查看", "generatePath", "role", "LLM", "画像", "阶段", "—", "P0"],
      ["陪练", "对话", "聊天", "simulate+score", "messages", "LLM", "—", "分数", "—", "P0"],
      ["测验", "考", "答题", "gradeQuiz", "answers", "LLM", "—", "解析", "—", "P0"],
    ],
    mainFlow: ["画像→路径→练→测→报告"],
    branchFlows: ["四角色陪练"],
    exceptionFlows: ["断线→保存进度"],
    humanFlows: ["HR 审核认证"],
    pages: [
      ["首页", "画像", "卡片", "进入", "—", "雷达图"],
      ["陪练", "对话", "聊天", "发送", "对方输入", "评分"],
      ["管理", "看板", "图表", "筛选", "—", "—"],
    ],
    prompts: promptPack("企业培训教练 Agent", "课程与话术"),
    finalNote: "培训 Agent 核心是练评闭环，不是内容搬运。",
  }),

  mod({
    slug: "paradigm-12",
    productName: "金融 AI 专家系统 Agent",
    oneLiner: "可引用、可复核的垂直行业专家智能体（金融场景）",
    businessBackground: "金融专业判断依赖经验，法规频繁更新，文档分散。",
    painPoints: ["查询成本高", "风险难以及时发现", "建议不可解释"],
    whyAgent: ["专业知识 RAG", "风险识别", "报告生成"],
    traditionalLimits: ["数据库只检索不推理", "纯模型不可审计"],
    agentValue: ["提效", "可解释", "人机协同"],
    targetUsers: ["客户经理", "风控", "合规", "顾问"],
    scenarios: ["尽调", "合同", "政策", "异常单"],
    boundaries: ["建议非终审"],
    notSolving: ["替代监管报送法律责任"],
    userNeedsTable: [
      ["角色", "业务要速度；风控要底线"],
      ["目标", "有据专业意见"],
      ["任务", "问/审/报告"],
      ["痛点", "怕担责"],
      ["高频", "问答", "风险点"],
      ["低频高价值", "大额授信"],
      ["成功", "引用正确、复核完成"],
    ],
    agentGoal: "提供专业可引用分析并触发专家复核",
    agentInputs: ["问题", "合同/尽调文本"],
    agentOutputs: ["结论", "风险", "报告", "复核单"],
    agentContext: ["法规", "案例", "内规"],
    agentTools: ["searchKnowledge", "detectRisks", "generateReport"],
    agentData: ["法规库", "授信系统"],
    agentReasoning: ["检索→分析→分级→复核门控"],
    agentWorkflow: ["问", "检索", "答", "风险", "复核"],
    agentExceptions: ["无法律依据→拒答"],
    humanConfirmNodes: ["所有中高风险结论", "对外报告"],
    featureModules: [
      ["问答", "专业", "提问", "generateAnswer", "q", "RAG", "—", "结构化", "—", "P0"],
      ["风险", "识别", "粘贴", "detectRisks", "text", "规则+LLM", "—", "风险表", "—", "P0"],
      ["复核", "人机", "审批", "submitReview", "review_id", "工作流", "待复核", "结论", "—", "P0"],
    ],
    mainFlow: ["分析→分级→复核→结论"],
    branchFlows: ["报告类型分支"],
    exceptionFlows: ["冲突法规→列出让专家选"],
    humanFlows: ["专家通过/驳回"],
    pages: [
      ["首页", "入口", "搜索", "提问", "—", "—"],
      ["复核", "审批", "表单", "通过", "—", "免责声明"],
    ],
    prompts: promptPack("持牌金融顾问 Agent", "法规与案例"),
    finalNote: "金融专家 Agent 中高风险必须专家复核。",
  }),

  mod({
    slug: "paradigm-13",
    productName: "ToB 通用 AI 工作台 Agent",
    oneLiner: "编排 RAG、文档、分析、Agent、风控的统一企业 AI 入口",
    businessBackground: "企业同时存在多种 AI 需求，烟囱式建设重复，治理困难。",
    painPoints: ["入口分散", "无统一权限审计", "PoC 难复用"],
    whyAgent: ["意图路由", "模块化能力", "统一治理"],
    traditionalLimits: ["单点 Chatbot", "无审批审计"],
    agentValue: ["快速定制", "合规一致"],
    targetUsers: ["业务", "主管", "管理员"],
    scenarios: ["统一 AI 门户", "行业 PoC"],
    boundaries: ["编排壳", "深度见各范式"],
    notSolving: ["替代所有垂直深度系统"],
    userNeedsTable: [
      ["角色", "业务要用；管理员要管"],
      ["目标", "一个入口多种能力"],
      ["任务", "输入→路由→结果→审批"],
      ["痛点", "不知道找哪个系统"],
      ["高频", "知识问", "分析"],
      ["低频高价值", "跨模块编排"],
      ["成功", "审计完整、审批到位"],
    ],
    agentGoal: "识别意图并调度合适能力模块完成任务",
    agentInputs: ["NL 任务", "角色", "业务对象"],
    agentOutputs: ["结构化结果", "工具轨迹", "审批单"],
    agentContext: ["权限", "历史任务", "模块注册表"],
    agentTools: ["classifyIntent", "ragSearch", "decomposeAgentTask"],
    agentData: ["知识库", "ERP", "审计库"],
    agentReasoning: ["分类→选模块→执行→治理检查"],
    agentWorkflow: ["输入", "路由", "执行", "审批", "审计"],
    agentExceptions: ["模块失败→降级"],
    humanConfirmNodes: ["高风险", "Agent 写操作"],
    featureModules: [
      ["工作台", "统一入口", "输入", "classify+run", "input", "Orchestrator", "登录", "任务", "—", "P0"],
      ["结果", "详情", "编辑", "generateAnswer", "task_id", "多模块", "—", "Answer", "—", "P0"],
      ["管理", "治理", "配置", "audit", "—", "—", "admin", "日志", "—", "P0"],
    ],
    mainFlow: ["工作台→任务→结果→历史"],
    branchFlows: ["五类意图各走模块"],
    exceptionFlows: ["权限拒绝"],
    humanFlows: ["审批流"],
    pages: [
      ["工作台", "首页", "指标+输入", "运行", "—", "场景卡"],
      ["任务", "执行", "意图标签", "执行", "进行中", "—"],
      ["管理", "后台", "日志表", "筛选", "—", "—"],
    ],
    prompts: promptPack("ToB 企业 AI 编排 Agent", "多域知识"),
    mvpTable: defaultMvp(
      ["工作台+五意图+权限+审批+审计"],
      ["全量 ERP 直连", "多租户"],
    ),
    finalNote: "通用工作台 Agent 是治理与编排层，垂直深度可插拔各范式。",
  }),
];
